# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e04b2c3d2dd11b19e869ce7ed7c387ba1d9de8a3f629a0eed55b82c158dbcf3a482da2219c306d7b163272a12fea89b3f52d01cd7a8c80bc1e2a51063e3138b1

test:
  secret_key_base: 9909c971e8bbf0be6a5190eea8b5d27c3b6c45ed2c67be66daaddc84e4f2f5010a0c46e86cbb245c94ecfa6e106dfb2ca9f6da1cbb3337e43487bbdfa56fee0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
